name: automerge
on:
  push:
    branches-ignore: 
      - 'master'
  pull_request:
    types:
      - labeled
  check_suite: 
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@135f0bdb927d9807b5446f7ca9ecc2c51de03c4a"
        with:
          args: "--trace"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKENS }}"
          MERGE_LABELS: "feature, error"
          MERGE_METHOD: "merge"
          MERGE_COMMIT_MESSAGE: "automerged"
          MERGE_FORKS: "false"
          MERGE_RETRIES: "6"
          MERGE_RETRY_SLEEP: "10000"
          UPDATE_LABELS: ""
          UPDATE_METHOD: ""
