name: Merge Pal (events)

on:
  push: {} # update PR when base branch is updated
  pull_request: # try to merge if labels have changed (white/black list)
    types:
      - labeled

jobs:
  # thats's all. single step is needed - if PR is mergeable according to
  # branch protection rules it will be merged automatically
  mergepal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: maxkomarychev/merge-pal-action@vX.Y.Z
        with:
          token: ${{ secrets.GITHUB_TOKENS }}
